import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, History, Package, CheckCircle } from 'lucide-react';
import { base44 } from '@/api/base44Client';

export default function AccountOrders() {
  const [orders, setOrders] = useState([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => { (async () => { const user = await base44.auth.me(); const data = await base44.entities.Order.filter({ buyer_email: user.email }, '-created_date', 100); setOrders(data); setLoading(false); })().catch(() => setLoading(false)); }, []);
  const confirm = async (order) => { const updated = await base44.entities.Order.update(order.id, { buyer_confirmed_received: true, status: order.seller_confirmed_delivery ? 'completed' : 'buyer_confirmed' }); setOrders(prev => prev.map(o => o.id === order.id ? { ...o, ...updated } : o)); };
  return <div className="min-h-screen bg-gradient-to-b from-[#0033CC] to-[#001a80] px-4 py-8 text-white"><div className="max-w-4xl mx-auto"><button onClick={() => window.history.back()} className="inline-flex items-center gap-2 text-white/70 hover:text-white mb-6"><ArrowLeft className="w-4 h-4" /> Back</button><div className="rounded-3xl bg-white text-slate-900 p-6 shadow-xl"><div className="flex items-center gap-3 mb-6"><div className="w-12 h-12 rounded-2xl bg-blue-100 flex items-center justify-center"><History className="w-6 h-6 text-blue-700" /></div><div><h1 className="font-heading font-bold text-2xl">My Orders</h1><p className="text-sm text-slate-500">Standalone order history</p></div></div>{loading ? <div className="py-16 text-center text-slate-400">Loading orders...</div> : orders.length === 0 ? <div className="py-16 text-center"><Package className="w-12 h-12 text-slate-200 mx-auto mb-3" /><p className="text-slate-500 mb-4">No orders yet.</p><Link to="/buysell" className="px-5 py-2 rounded-xl bg-blue-600 text-white font-bold">Browse listings</Link></div> : <div className="space-y-3">{orders.map(order => <div key={order.id} className="flex items-center gap-3 p-4 rounded-2xl border border-blue-100 bg-blue-50/40">{order.listing_image && <img src={order.listing_image} alt="" className="w-16 h-16 rounded-xl object-cover" />}<div className="flex-1"><p className="font-bold">{order.listing_title}</p><p className="text-sm text-blue-700">{order.price_label}</p><p className="text-xs text-slate-500">Seller: {order.seller_name}</p></div><div className="text-right"><span className="px-2 py-1 rounded-full bg-blue-100 text-blue-700 text-xs font-bold capitalize">{order.status?.replace(/_/g, ' ') || 'pending'}</span>{order.status !== 'completed' && order.status !== 'cancelled' && !order.buyer_confirmed_received && <button onClick={() => confirm(order)} className="mt-2 flex items-center gap-1 px-3 py-1.5 rounded-xl bg-blue-600 text-white text-xs font-bold"><CheckCircle className="w-3 h-3" /> Confirm received</button>}</div></div>)}</div>}</div></div></div>;
}